version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - ./storage/postgres/data:/data:delegated
    networks:
      - nestjs-course
  

volumes:
  postgres_data:

networks:
  nestjs-course:
